---
title: simulating meta-analysis data
author: Charles T. Gray
date: '2018-07-27'
draft: true
slug: simulating-meta-analysis-data
categories:
  - statistics
tags:
  - 3c^2
  - simulations
---


```{r packages, message=FALSE}
# packages

library(tidyverse)

```


## meta-parameters

I want to (re)run trials of simulations for:

- different sample sizes
- different distributions
- (also different arm adjustment in the meta-analysis simulation)

```{r}
meta_parameters <- list(
  sample_size = c(15, 30),
  distribution = list(
    list(
      dist = "exp",
      pars = list(rate = 2)
    ),
    list(
      dist = "lnorm",
      pars = list(meanlog = 2, sdlog = 1)
    )
  )
) %>% purrr::cross()

# take a look
meta_parameters %>% str(2)

```




# some other crap from before

## function

```{r}

to_fn <- function(string, type = "d") {
  fn <- paste(type, string, sep = "") %>% rlang::sym()
  fn
}
  


```


## experiment: can I bind 

```{r}
# can use stringr to bind strings?


# then convert to function?



```


## bind the distributions to a list

```{r}



```


## single-study simulation

### a trial

> go back to 


## meta-analysis simulation