---
title: "measures."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

# packages
library(googlesheets)
library(tidyverse)

# get data

# register the sheet
measures <- gs_title("measures")

# extract data from the sheet
measures_data <- measures %>% 
  gs_read(ws = "daily_record") %>% # convert to tibble
  arrange(date) # because sometimes I get behind in entries

```

```{r set vis parameters}

alpha <- 0.5

```


```{r long form}

# all data in long form by type
measures_long <- measures_data %>%
  mutate(phi = map2(phi, phi_goal, function(x, y) list(x, y)),
         theta = map2(theta, theta_goal, function(x, y) list(x, y)),
         varphi = map2(varphi, varphi_goal, function(x, y) list(x, y))) %>% 
  select(-phi_goal, -theta_goal, -varphi_goal) %>% 
  gather(key = "type",
         value = "poms",
         phi, theta, varphi) %>% 
  mutate(goal = map(poms, 2),
         poms = map_dbl(poms, 1))

```

```{r goals data}
# isolate observations where I set a goal
goals_data <- measures_long %>% 
  filter(goal != "no record") %>% 
  mutate(goal = as.double(goal),
         success = poms >= goal)



```

***

```{r filled barchart over time}
measures_long %>% 
  ggplot(aes(x = date, y = poms, fill = type)) + 
  geom_bar(stat = "identity", alpha = alpha) +
  scale_y_continuous(breaks = 1) +
  scale_fill_grey() +
  labs(title = "deep work over time ",
       x = "poms := 20 minutes"
    # title = "[deep work](http://calnewport.com/books/deep-work/) over time"#, 
      #  caption = paste0(
      #    "pom is currently ",
      #    measures_data$pom[[nrow(measures_data)]],
      #    " minutes.\n\n,"
      # "phi := phd, i.e., working on papers; 
      #  theta := skills building, as distinct to what is required from current papers. 
      #  varphi := puzzles; i.e., general admin.")
      )

```

I [like](post/2018-07-06-index-cards-bujo-pomodoros) Newport's term [*deep work*](http://calnewport.com/books/deep-work/).  

***

How I'm going today:

```{r fig.align='center'}
# today's goals
goals_data %>% 
  filter(date == lubridate::today() | 
           date == lubridate::today() - 1) %>% 
  select(type, poms, goal, success) %>% 
  knitr::kable(caption = "today's goals", align = "lccr")

```

***

```{r goals}
goals_data %>% 
  ggplot(aes(x = date)) +
  geom_bar(aes(y = poms, fill = mood), stat = "identity", alpha = alpha) +
  geom_point(aes(y = goal)) +
  facet_grid(type ~ .) +
  labs(title = "barchart of work completed, with points for goals set") + 
  scale_fill_grey()

```

***

```{r recent observations, fig.cap="most recent observations"}

# take a look at the most recent records
measures_data %>% tail() 
# %>% knitr::kable(caption = "Most recent observations.")

```

