---
title: "about"
author: "Charles T. Gray"
date: "26 June 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I've moved house twice in the last year and it's taken a toll. In the meantime, I'm still working on my doctorate in, for want of a formal term, statistical data science. A tidy statistician, perhaps. 

I need to muster all my tools for keeping sane as I weather the aftershocks of the housing crisis with this newfound stabiltiy. 

I think blogging daily will help me organise my thoughts. I suspect it'll be too introspective to be worth subscribing to. Eventually there might be something in the projects that is useful or interesting. Not making any apologies, as this blog is, like my twitter account, one woman screaming into the void. 

You can read my short [professional bio](https://docs.google.com/document/d/11ugjrQilujrHQHra2mukwEu62JBzImugWP67SBETUSE/edit?usp=sharing), or about my role as a [mathbassador](http://choosemaths.org.au/charles-gray/), for which we made a [short film](https://www.youtube.com/watch?v=o0Rqz8Hgacc&feature=youtu.be&ab_channel=AMSITubn).

I was stalled on deploying my blog until I came across Alison's [fantastic post](https://alison.rbind.io/post/up-and-running-with-blogdown/#in-github) on getting a [`blogdown`](https://bookdown.org/yihui/blogdown/) site up and running.  
