---
title: if we're really committed to diversity, crying should be okay
author: Charles T. Gray with Mark Padgham and Katherine Firth
date: '2018-07-18'
slug: crying-should-be-okay
categories:
  - outreach
tags:
  - diversity
  - c-ptsd
---

I believe that all people struggle with adulting, and that no one is perfect. Although my lifetime has shaped me as noticably different to many people, for the first time in a long while I feel I've been able to make use of my strengths.

<center>
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">**never** been so proud <a href="https://twitter.com/hashtag/choosemaths?src=hash&amp;ref_src=twsrc%5Etfw">#choosemaths</a> <a href="https://t.co/8gptuDY4Dy">https://t.co/8gptuDY4Dy</a></p>&mdash; Charles T. Gray (@cantabile) <a href="https://twitter.com/cantabile/status/1018676269074923520?ref_src=twsrc%5Etfw">July 16, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>

I may seem different but, to employ statistical parlance, conditioning on a lifetime of being socially demeaned[^1], my bias from the point estimate of the expected value approximates zero. [I am a textbook case](https://en.wikipedia.org/wiki/Forgotten_Australians).


It has helped me arrive at this. If we truly care about diversity in our community, then we need to allow for emotional diversity, too. Data science is just beginning to take off, and we have the unique opportunity of being there for what a community member I recently met called *The Golden Age of R*. 

How do we build empathy into our community as it grows?    

---

I live with [complex post traumatic stress disorder](https://www.sane.org/the-sane-blog/mental-illness/what-is-complex-ptsd) and, among other things, despite my best efforts and a lifetime of therapy, I have a propensity for displays of emotion that transgress established mores. *Especially* the mores of emotion established in the disciplines of piano, mathematics, statistics, and computer science.

When you endure trauma for a sustained amount of time, it can leave you with physical waves of what feels like an ocean of pain inside. It took me a very long time to learn that these waves do pass, and the more I accept that, the shorter and more infrequent they become.   

I am far from perfecting my coping mechanisms, but my efforts have resulted in a truly amazing lifetime so far[^2]. 


---

I struggle to escape painful memories, so mindful techniques for bringing myself back to the present moment are very useful to me. I use many things to cope: bullet journalling, complex productivity systems, yoga, walking, crafting, alcohol, talk therapy. 

More than anything, **I use work to cope**. And it has been stunningly effective. Thus, I have the isolating conundrum of owing my success to painful experiences that few I encounter in my working life can relate to.

I spent twenty years as a musician, because I found the practice of music very soothing. I need my work to soothe me, or life would be unbearable. This is not the kind of disease you can cure, and it is easy for life's little inadvertant incidences to trigger unwanted reminiscences. So, I must practice constant self-healing.  

Extreme trauma coping mechanisms aren't all bad. I'd read more books by the time I was fourteen than most adults I meet. I spent five years as a political activist, screaming down megaphones and occupying buildings. I studied at one of the most prestigious music institutions in the country, and spent a decade as a professional pianist. I hitchhiked Australia for three years, and backpacked through South India, alone. I've published short works of fiction, and arranged music for chamber orchestras. 

I fell in love with mathematics, and now do a great deal of public speaking where I share my passion for mathematical science with other women. I have lectured more subjects and done more teaching from pure mathematics to applied statistics than any other phd student I've encountered. 

I am now writing my third thesis. My first was in postcolonial film musicology, the second a category theory framed question that shifted a mathematical ordering system from graphs to algebras, and my third, in progress, is in statistical data science.

---

I believe my unusual life has left me with more positive quirks than negative. Recently, through the community, I've begun sharing my teaching and collaboration ideas, with a strong focus on inclusivity, and it's been really positive. I believe emotional diversity can enrich the community, especially in fostering empathy.  

And that's why I think 'diversity' needs to go beyond the colour of our skin or the gender box we tick on a form. Diversity needs to include everyone, at every point in their lives. When a beloved family member has died, when yet another person is being impacted by sexual harassment or bullying, when we've faced an inexplicable and horrific university politics that deprives a fantastic person of their grant. 

Emotional intensity can power an intellectual and professionally challeging career--so we should support people with high EQ along with those with high IQ. It's okay to cry, when crying is the intelligent option. If we dismiss those who cry as overly 'emotional', we'll never get emotional intelligence into our apps, our code, our programming. If we're really committed to diversity, crying should be okay. 


[^1]: I now realise I need not be ashamed of why I changed my name. I changed my first name initially, and then at twenty-five, all of it. Why? Because I realised that for a decade no one I had known before I called the cops and walked out of my parents house wanted to know me. I made them uncomfortable, and my pain made them uncomfortable, so they avoided me, unwittingly repeating the behaviour of everyone who knew me. I changed my name because my name didn't matter to anyone, and I was completely alone. So the one perk I had in the situation was to choose any name I liked. Make lemonade, and all that.   

[^2]: Recently this was epitomised by delivering a useR! workshop directly across the road from the Conservatorium where I performed twenty years ago at the Brisbane Women's Composers concert in 1998. 
