---
title: if we're really committed to diversity, then we should privilege agency
author: Charles T. Gray
date: '2018-09-26'
slug: if-we-re-really-committed-to-diversity-then-we-should-privilege-agency
categories:
  - diversity
tags:
  - grrr
---

You know, I am not surprised one whit by the success of the men's sheds movement

> [whose primary activity is the provision of a safe, friendly and healing environment where men are able to work on meaningful projects at their own pace in their own time in the company of other men](https://mensshed.org/about-amsa/what-is-amsa/) 

and where

> "men don’t talk face to face(,) they talk shoulder to shoulder."

I recently worked on a scraping algorithm component for a larger project with a couple of ecologists. I got stumped on a really, really specific thing, and posted a question to the R-Ladies forum. Jenny Bryan was extraordinarily helpful, and I learnt a great deal from the project. It was thrilling to do real research with real scientists, and it really did feel we all were having a smashing time of it. This project is a follow-on from the [Evidence Synthesis Hackathon](https://evidencesynthesishackathon.com/).

I was so buoyed by the normalising effect of the ecologists' company, and the newfound community of R-Ladies, I got more mathematics done that week than I had for months.  

I recently wrote about how I use work to cope. 
One way I facilitate this is to engage in professional societies; I enjoy talking about tools, statistics, mathematics, and programming. Thus, I enjoy socialising and working on projects with people who enjoy those things, too. Some people join a fishing club, or a men's shed[^1].

[^1]: My drawing solace in this ostensibly masculine way, to me, underscores why we should dispense with such terms altogether. 

Since the events leading up to the [eponymous crying](http://cantabile.rbind.io/2018/07/18/crying-should-be-okay/)[^2], I have experienced several interactions where I have been excluded from discussions and decisions that pertained to me, as well as projects within some organisations with whom I am affiliated. 

[^2]: The eponymous crying was, for the record, primarily a *metaphor*.

I have no doubt that people are well intentioned to the hilt. But removing one of the most useful tools for coping with c-ptsd that I have seems like an awfully strange way of helping me out.  

And think of the implicit message, that you believe that I am incapable of making rational decisions for myself? Permit me to drop some knowledge from the school of hard knocks, that type of power imbalance is a recipe for a toxic relationship. Furthermore, the silence that accompanies making decisions for other people renders the issue seemingly taboo.   

If we're really commited to diversity, then it needs to begin and end with agency.  It is a dark world, indeed, where we feel we can unilaterally decide for another person was is within their capabilities or to their benefit or detriment.  

I will be stepping aside from organisations that do not privilege agency, as I believe respecting others' agency is the one of the foremost ways we demonstrate fundamental respect for another person. I will now prioritise organisations[^3] who welcome and nuture those who find healing through their engagement with the shared interests within the community. I will find my own figurtive men's sheds. 

[^3]: such as R-Ladies.

Through my tears, some time back, I asked a male friend, "is this how it happens?" Is this how women get driven out of data science? 

You fucking betcha. 
