---
title: simulating meta-analysis data
author: Charles T. Gray
date: '2018-07-07'
slug: simulating-meta-analysis-data
categories:
  - r-coding
tags:
  - simulations
  - meta-analysis
  - tidyverse
draft: true
---

```{r load packages, message=FALSE}
# packages
library(tidyverse)
```

```{r}
# set a seed so these results are reproducible
set.seed(38)

```


## Write a `purrr::rerun` simulation

So, I suppose we want to create a meta-analysis.

We need to take two samples... 

### Try it with the single-study setting first

In this case we wish to produce `trials` worth of samples. 

Calculate the confidence intervals. 


#### The function

```{r}
# sketch the function first

# this will go to purrr::rerun
trials = 10 # number of replications

# things i'd like to compare over simulations
n = 30 # sample size

# i'm not sure about this whole evaluation thing. is there a better way?
dist = "lnorm" # distribution
parameters = list(meanlog = 1, sdlog = 0.5) # how vectorisable is this bit?

# what does this desnity look like?
tibble(x = c(-1, 1)) %>% 
  ggplot(aes(x = x)) +
  stat_function(fun = dlnorm, args = parameters)

# so, one run 
rlnorm(n, meanlog = parameters$meanlog, sdlog = parameters$sdlog) %>% 
  summary()

```

### Evaluation of functions

## Unpicking whatever I did way back when

### From code to maths again 

