---
title: A coding workshop without code
author: Charles T. Gray
date: '2018-06-17'
slug: a-coding-workshop-without-code
categories:
  - teaching
tags:
  - tidyverse
---

I'm currently working on [R-Curious](https://github.com/softloud/rcurious), a workshop hosted by [R-Ladies](https://rladies.org/). 

Something that bothers me about workshop convention is the trap of copy and paste code. I want to develop a system of pseudo code that is easily discernable by newbies. I wonder if something like this already exists?

As a piano teacher, I found it was dramatic how important it was to make sure the student was doing, thinking for themselves. I have seem people beside me at workshops run code and declare they have learnt a great deal. However, simply running someone else's code only demonstrates that they know how to write it and you know how to run it. 

As an educator, I think this is the question that has most interested me in the last six years of lecturing and speaking. I don't have a solution, but I'm going to experiment with how *little* prescriptive code I can have in my workshop.

In a workshop environment, can't we all use cheatsheets and tutorials, just as we do when we are working alone? Why not have searching for solutions online be part of the workshop? 

But now I fret that not everyone will have internet access. 